name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Release
        run: |
          npx standard-version

          # Push the new tag and release commit
          git push --follow-tags origin master

  # You can add more jobs or customize the existing one as needed

options:
  name-template: 'v$RESOLVED_VERSION 🌈'
  tag-template: 'v$RESOLVED_VERSION'
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
    - title: '🧰 Maintenance'
      label: 'chore'
  change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
  change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
  version-resolver:
    major:
      labels:
        - 'major'
    minor:
      labels:
        - 'minor'
    patch:
      labels:
        - 'patch'
    default: patch
  template: |
    ## Changes

    $CHANGES
