name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  pre-release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & test
        run: echo done!

      - name: Create Release
        id: create_release
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0)
          echo "Previous Tag: $PREVIOUS_TAG"
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1.0.${{ github.run_number }}"
          # automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}













# name: Release

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - master

# jobs:
#   pre-release:
#     name: Release
#     runs-on: "ubuntu-latest"

#     steps:
#       - name: "Build & test"
#         run: |
#           echo done!

#       - uses: marvinpinto/action-automatic-releases@latest
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "latest"
#           prerelease: true
#           title: "Development Build"
#           files: |
#             LICENSE.txt
#             *.jar
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
